# Generated by Django 3.2.13 on 2024-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_task', '0003_alter_task_input_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortask',
            name='task_output',
            field=models.TextField(null=True),
        ),
    ]
