# Generated by Django 4.2.20 on 2025-10-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_task', '0006_alter_historicalinstructortaskschedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortask',
            name='task_output',
            field=models.TextField(null=True),
        ),
    ]
