name: CI - Quality Checks

### TODO: Update this flow from edx-platfrom branch
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
      - master
  workflow_dispatch

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Dummy Test
        run: echo 'Add code quality checks here'

  local-translations-check:
    name: Local Translation Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
